feat: Setup test report action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,4 +42,12 @@ jobs:
         run: make migrate
 
       - name: Test
-        run: make test
+        run: make test-report
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Go Tests            # Name of the check run which will be created
+          path: test-report.xml     # Path to test results
+          reporter: jest-junit      # Format of test results
