feat: Setup test report (#7)
* feat: Add command to generate test report

* chore: Ignore generated content

* feat: Setup test report action

* feat: Improve build and push workflow (#10)

* fix: Use permissions

* fix: Permission should set in jobs context

* feat: Specify github token

* feat: Use github.sha and push trigger

* chore: Remove push trigger

* feat: Add gh ext act command (#8)

* feat: Use docker metadata action (#11)

* feat: Use docker metadata action

* chore: Insert branches

* feat: Setup title and description

* feat: Supply labels by github actions

* chore: Fix licenses

* feat: Separate to report

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,4 +42,11 @@ jobs:
         run: make migrate
 
       - name: Test
-        run: make test
+        run: make test-report
+
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: test-report.xml
+
